using IepAssistant.Domain.Entities;
using IepAssistant.Services.Models;

namespace IepAssistant.Api.Seeding;

/// <summary>
/// The fictional "Maple Ridge Local Schools" district <see cref="DemoSeeder"/> builds: every school,
/// staff member, student and family, written out explicitly rather than generated by modulo arithmetic,
/// so the demo district is reviewable as a roster and identical on every run. Nothing here touches the
/// database — <see cref="DemoSeeder"/> drives the real application services from these rows.
///
/// Changing who exists here also means updating <c>docs/demo/maple-ridge-demo-district.md</c> and its
/// login spreadsheet, which are snapshots of this roster. <see cref="Validate"/> catches the
/// contradictions a roster edit can introduce; <c>DemoRosterTests</c> runs it.
/// </summary>
public static class DemoRoster
{
    public const string DistrictName = "Maple Ridge Local Schools";
    public const string StateCode = "OH";
    public const string EmailDomain = "mapleridge.example";

    /// <summary>Which building, addressed by index into <see cref="Schools"/>.</summary>
    public const int Elementary = 0;
    public const int Middle = 1;
    public const int High = 2;

    public sealed record SchoolSpec(string Name, string GradeRange);

    public static readonly SchoolSpec[] Schools =
    {
        new("Maple Ridge Elementary", "K-5"),
        new("Maple Ridge Middle School", "6-8"),
        new("Maple Ridge High School", "9-12")
    };

    // ----------------------------------------------------------------------------------------- Staff

    /// <param name="SchoolIndex">Home building. Null only for the district admin (the one role a staff
    /// invite must NOT carry a school for — see StaffInviteService). A RelatedServiceProvider keeps a home
    /// building but may serve students in any of them.</param>
    /// <param name="Title">The job title a district would actually print, used as the login table's role label.</param>
    public sealed record StaffSpec(string FirstName, string LastName, int OrgRoleId, int? SchoolIndex, string Title)
    {
        public string Email => $"{FirstName.ToLowerInvariant()}.{LastName.ToLowerInvariant()}@{EmailDomain}";
    }

    public static readonly StaffSpec DistrictAdmin =
        new("Dana", "Whitfield", OrgRoleIds.DistrictAdmin, null, "Director of Special Education (District Admin)");

    /// <summary>Everyone except <see cref="DistrictAdmin"/>, who is created by district registration instead
    /// of by invite. Ordered the way the login table should read.</summary>
    public static readonly StaffSpec[] Staff =
    {
        new("Priya", "Raman", OrgRoleIds.SchoolAdmin, Elementary, "Principal, Maple Ridge Elementary"),
        new("Marcus", "Boyd", OrgRoleIds.SchoolAdmin, Middle, "Principal, Maple Ridge Middle School"),
        new("Helen", "Osei", OrgRoleIds.SchoolAdmin, High, "Principal, Maple Ridge High School"),

        new("Jordan", "Rivera", OrgRoleIds.Teacher, Elementary, "Intervention Specialist, Elementary"),
        new("Alicia", "Moreno", OrgRoleIds.Teacher, Elementary, "Intervention Specialist, Elementary"),
        new("Morgan", "Chen", OrgRoleIds.Teacher, Middle, "Intervention Specialist, Middle School"),
        new("Derek", "Vaughn", OrgRoleIds.Teacher, Middle, "Intervention Specialist, Middle School"),
        new("Casey", "Nguyen", OrgRoleIds.Teacher, High, "Intervention Specialist, High School"),
        new("Tasha", "Bell", OrgRoleIds.Teacher, High, "Intervention Specialist, High School"),

        new("Sam", "Okafor", OrgRoleIds.RelatedServiceProvider, Elementary, "Speech-Language Pathologist (all buildings)"),
        new("Robin", "Alvarez", OrgRoleIds.RelatedServiceProvider, Elementary, "Occupational Therapist (all buildings)"),
        new("Noor", "Haddad", OrgRoleIds.RelatedServiceProvider, High, "Physical Therapist (all buildings)"),
        new("Elena", "Vogel", OrgRoleIds.RelatedServiceProvider, Middle, "School Psychologist (all buildings)"),

        new("Avery", "Thompson", OrgRoleIds.GeneralEducator, Elementary, "General Education Teacher, Elementary"),
        new("Riley", "Patel", OrgRoleIds.GeneralEducator, Middle, "General Education Teacher, Middle School"),
        new("Devon", "Brooks", OrgRoleIds.GeneralEducator, High, "General Education Teacher, High School")
    };

    /// <summary>Case managers for a building, in the order students are dealt to them.</summary>
    public static IEnumerable<StaffSpec> CaseManagersAt(int schoolIndex) =>
        Staff.Where(s => s.OrgRoleId == OrgRoleIds.Teacher && s.SchoolIndex == schoolIndex);

    public static StaffSpec Slp => Staff.First(s => s.LastName == "Okafor");
    public static StaffSpec OccupationalTherapist => Staff.First(s => s.LastName == "Alvarez");
    public static StaffSpec PhysicalTherapist => Staff.First(s => s.LastName == "Haddad");
    public static StaffSpec Psychologist => Staff.First(s => s.LastName == "Vogel");

    // --------------------------------------------------------------------------------------- Students

    /// <summary>Where a student sits in the special-education process — which decides what documents,
    /// evaluation case and meetings the seeder creates for them.</summary>
    public enum Track
    {
        /// <summary>On an IEP: one finalized IEP with goals and progress data.</summary>
        EstablishedIep,

        /// <summary>Just reevaluated: a finalized ETR followed by a finalized IEP.</summary>
        IepWithRecentEtr,

        /// <summary>Newly found eligible: an IEP being written right now, not yet finalized.</summary>
        DraftIep,

        /// <summary>Initial evaluation finished: consent on file, finalized ETR, eligibility determined,
        /// and the first IEP started from it.</summary>
        EvaluationEtrComplete,

        /// <summary>Initial evaluation running: referral and consent, no documents yet.</summary>
        EvaluationInProgress
    }

    /// <param name="Disability">Null for a student still being evaluated — no category has been determined yet.</param>
    public sealed record StudentSpec(
        string FirstName,
        string LastName,
        int SchoolIndex,
        GradeLevel Grade,
        DisabilityCategory? Disability,
        Track Track);

    /// <summary>
    /// 42 students across the three buildings: 35 finalized IEPs, 3 IEPs in progress, 6 ETRs, 4 open
    /// evaluation cases. The disability mix follows IDEA's real shape (specific learning disability is the
    /// largest group by far, then speech/language, autism and other health impairment, with the
    /// low-incidence categories appearing once each) so caseload and compliance screens look like a
    /// district's rather than a round-robin over the enum.
    /// </summary>
    public static readonly StudentSpec[] Students =
    {
        // ---- Maple Ridge Elementary (K-5) ----
        new("Aiden", "Bennett", Elementary, GradeLevel.K, DisabilityCategory.DevelopmentalDelay, Track.EstablishedIep),
        new("Bella", "Carter", Elementary, GradeLevel.K, DisabilityCategory.SpeechOrLanguageImpairment, Track.EstablishedIep),
        new("Carlos", "Diaz", Elementary, GradeLevel.G1, DisabilityCategory.SpeechOrLanguageImpairment, Track.EstablishedIep),
        new("Daniela", "Flores", Elementary, GradeLevel.G1, DisabilityCategory.DevelopmentalDelay, Track.IepWithRecentEtr),
        new("Ethan", "Grant", Elementary, GradeLevel.G2, DisabilityCategory.Autism, Track.EstablishedIep),
        new("Fiona", "Hayes", Elementary, GradeLevel.G2, DisabilityCategory.SpecificLearningDisability, Track.EstablishedIep),
        new("Owen", "Sanders", Elementary, GradeLevel.G2, null, Track.EvaluationInProgress),
        new("Gavin", "Ibarra", Elementary, GradeLevel.G3, DisabilityCategory.SpecificLearningDisability, Track.EstablishedIep),
        new("Hannah", "Kim", Elementary, GradeLevel.G3, DisabilityCategory.OtherHealthImpairment, Track.EstablishedIep),
        new("Isaac", "Lopez", Elementary, GradeLevel.G3, DisabilityCategory.SpeechOrLanguageImpairment, Track.EstablishedIep),
        new("Julia", "Mitchell", Elementary, GradeLevel.G4, DisabilityCategory.SpecificLearningDisability, Track.IepWithRecentEtr),
        new("Kaleb", "Novak", Elementary, GradeLevel.G4, DisabilityCategory.Autism, Track.EstablishedIep),
        new("Layla", "Ortiz", Elementary, GradeLevel.G4, DisabilityCategory.HearingImpairment, Track.EstablishedIep),
        new("Paloma", "Torres", Elementary, GradeLevel.G4, DisabilityCategory.SpecificLearningDisability, Track.EvaluationEtrComplete),
        new("Mason", "Parker", Elementary, GradeLevel.G5, DisabilityCategory.SpecificLearningDisability, Track.EstablishedIep),
        new("Nadia", "Reyes", Elementary, GradeLevel.G5, DisabilityCategory.EmotionalDisturbance, Track.EstablishedIep),

        // ---- Maple Ridge Middle School (6-8) ----
        new("Quentin", "Underwood", Middle, GradeLevel.G6, DisabilityCategory.SpecificLearningDisability, Track.EstablishedIep),
        new("Ruby", "Vance", Middle, GradeLevel.G6, DisabilityCategory.OtherHealthImpairment, Track.EstablishedIep),
        new("Samuel", "Whitaker", Middle, GradeLevel.G6, DisabilityCategory.Autism, Track.EstablishedIep),
        new("Talia", "Xiong", Middle, GradeLevel.G6, DisabilityCategory.SpeechOrLanguageImpairment, Track.EstablishedIep),
        new("Destiny", "Hollis", Middle, GradeLevel.G6, DisabilityCategory.SpecificLearningDisability, Track.EvaluationEtrComplete),
        new("Uriel", "Yates", Middle, GradeLevel.G7, DisabilityCategory.SpecificLearningDisability, Track.IepWithRecentEtr),
        new("Violet", "Zamora", Middle, GradeLevel.G7, DisabilityCategory.EmotionalDisturbance, Track.EstablishedIep),
        new("Wesley", "Abbott", Middle, GradeLevel.G7, DisabilityCategory.SpecificLearningDisability, Track.EstablishedIep),
        new("Ximena", "Bright", Middle, GradeLevel.G7, DisabilityCategory.IntellectualDisability, Track.EstablishedIep),
        new("Caleb", "Gibbs", Middle, GradeLevel.G7, null, Track.EvaluationInProgress),
        new("Yusuf", "Castillo", Middle, GradeLevel.G8, DisabilityCategory.OtherHealthImpairment, Track.EstablishedIep),
        new("Zoe", "Dunn", Middle, GradeLevel.G8, DisabilityCategory.SpecificLearningDisability, Track.DraftIep),
        new("Adrian", "Ellis", Middle, GradeLevel.G8, DisabilityCategory.Autism, Track.EstablishedIep),
        new("Brooke", "Fowler", Middle, GradeLevel.G8, DisabilityCategory.MultipleDisabilities, Track.EstablishedIep),

        // ---- Maple Ridge High School (9-12) ----
        new("Elias", "Iverson", High, GradeLevel.G9, DisabilityCategory.SpecificLearningDisability, Track.EstablishedIep),
        new("Faith", "Jennings", High, GradeLevel.G9, DisabilityCategory.OtherHealthImpairment, Track.EstablishedIep),
        new("Gabriel", "Kowalski", High, GradeLevel.G9, DisabilityCategory.Autism, Track.EstablishedIep),
        new("Simone", "Tate", High, GradeLevel.G9, DisabilityCategory.TraumaticBrainInjury, Track.DraftIep),
        new("Harper", "Larkin", High, GradeLevel.G10, DisabilityCategory.SpecificLearningDisability, Track.IepWithRecentEtr),
        new("Ian", "Marsh", High, GradeLevel.G10, DisabilityCategory.EmotionalDisturbance, Track.EstablishedIep),
        new("Jasmine", "Nash", High, GradeLevel.G10, DisabilityCategory.IntellectualDisability, Track.EstablishedIep),
        new("Kevin", "Olsen", High, GradeLevel.G11, DisabilityCategory.SpecificLearningDisability, Track.EstablishedIep),
        new("Lucia", "Pruitt", High, GradeLevel.G11, DisabilityCategory.VisualImpairment, Track.EstablishedIep),
        new("Oscar", "Silva", High, GradeLevel.G11, DisabilityCategory.SpecificLearningDisability, Track.DraftIep),
        new("Malik", "Quintero", High, GradeLevel.G12, DisabilityCategory.SpecificLearningDisability, Track.EstablishedIep),
        new("Nora", "Ramsey", High, GradeLevel.G12, DisabilityCategory.OrthopedicImpairment, Track.EstablishedIep)
    };

    // ---------------------------------------------------------------------------------------- Families

    public enum FamilyEngagement
    {
        /// <summary>Linked, sent the IEP draft to review, and has replied on it.</summary>
        ReviewedDraft,

        /// <summary>Linked and can see the record; has not been sent a draft.</summary>
        Linked,

        /// <summary>Invited but has not accepted yet — the pending-invite state a district chases.</summary>
        InvitePending
    }

    /// <param name="StudentIndex">Index into <see cref="Students"/> — the child this parent is linked to.</param>
    public sealed record ParentSpec(string FirstName, string LastName, int StudentIndex, FamilyEngagement Engagement)
    {
        public string Email => $"{FirstName.ToLowerInvariant()}.{LastName.ToLowerInvariant()}@{EmailDomain}";
    }

    /// <summary>Parents share their child's surname, so the family view reads like a real one.</summary>
    public static readonly ParentSpec[] Parents =
    {
        new("Jamie", "Bennett", 0, FamilyEngagement.ReviewedDraft),
        new("Alexis", "Hayes", 5, FamilyEngagement.ReviewedDraft),
        new("Monique", "Kim", 8, FamilyEngagement.Linked),
        new("Victor", "Mitchell", 10, FamilyEngagement.Linked),
        new("Sonia", "Underwood", 16, FamilyEngagement.Linked),
        new("Andre", "Castillo", 26, FamilyEngagement.Linked),
        new("Rosa", "Iverson", 30, FamilyEngagement.Linked),
        new("Deborah", "Silva", 39, FamilyEngagement.InvitePending)
    };

    /// <summary>The one student account: a high-schooler who takes part in their own transition planning.</summary>
    public const int StudentAccountStudentIndex = 37; // Kevin Olsen, grade 11
    public const string StudentAccountFirstName = "Kevin";
    public const string StudentAccountLastName = "Olsen";
    public static string StudentAccountEmail => $"kevin.olsen.student@{EmailDomain}";

    // -------------------------------------------------------------------------------------- Validation

    /// <summary>
    /// Fails fast on a roster that contradicts itself, so a future edit here is caught before a seed run
    /// touches a live database: a parent linked to the wrong child, a duplicated email, a student in a
    /// building whose grade band does not contain their grade, or a building missing staff every student
    /// there needs on their team. Called by <c>DemoSeeder.SeedAsync</c> and covered by unit tests.
    /// </summary>
    public static void Validate()
    {
        foreach (var parent in Parents)
        {
            if (parent.StudentIndex < 0 || parent.StudentIndex >= Students.Length)
                throw new InvalidOperationException($"Demo roster: parent '{parent.FirstName} {parent.LastName}' points at student index {parent.StudentIndex}, which does not exist.");
            var child = Students[parent.StudentIndex];
            if (child.LastName != parent.LastName)
                throw new InvalidOperationException($"Demo roster: parent '{parent.FirstName} {parent.LastName}' is linked to '{child.FirstName} {child.LastName}' — surnames must match so the family view reads correctly.");
        }

        if (StudentAccountStudentIndex < 0 || StudentAccountStudentIndex >= Students.Length)
            throw new InvalidOperationException($"Demo roster: the student account points at student index {StudentAccountStudentIndex}, which does not exist.");
        var studentAccount = Students[StudentAccountStudentIndex];
        if (studentAccount.FirstName != StudentAccountFirstName || studentAccount.LastName != StudentAccountLastName)
            throw new InvalidOperationException($"Demo roster: the student account is named '{StudentAccountFirstName} {StudentAccountLastName}' but student index {StudentAccountStudentIndex} is '{studentAccount.FirstName} {studentAccount.LastName}'.");

        var emails = Staff.Select(s => s.Email)
            .Concat(new[] { DistrictAdmin.Email, StudentAccountEmail })
            .Concat(Parents.Select(p => p.Email))
            .ToList();
        var duplicate = emails.GroupBy(e => e, StringComparer.OrdinalIgnoreCase).FirstOrDefault(g => g.Count() > 1);
        if (duplicate != null)
            throw new InvalidOperationException($"Demo roster: '{duplicate.Key}' is used by more than one account.");

        if (DistrictAdmin.SchoolIndex != null)
            throw new InvalidOperationException("Demo roster: a District Admin invite must not carry a school (see StaffInviteService).");

        for (var schoolIndex = 0; schoolIndex < Schools.Length; schoolIndex++)
        {
            if (!CaseManagersAt(schoolIndex).Any())
                throw new InvalidOperationException($"Demo roster: '{Schools[schoolIndex].Name}' has no Teacher to act as a case manager.");
            if (!Staff.Any(s => s.OrgRoleId == OrgRoleIds.SchoolAdmin && s.SchoolIndex == schoolIndex))
                throw new InvalidOperationException($"Demo roster: '{Schools[schoolIndex].Name}' has no School Admin to act as the LEA representative.");
            if (!Staff.Any(s => s.OrgRoleId == OrgRoleIds.GeneralEducator && s.SchoolIndex == schoolIndex))
                throw new InvalidOperationException($"Demo roster: '{Schools[schoolIndex].Name}' has no General Educator.");
        }

        foreach (var staff in Staff)
            if (staff.SchoolIndex == null || staff.SchoolIndex < 0 || staff.SchoolIndex >= Schools.Length)
                throw new InvalidOperationException($"Demo roster: '{staff.FirstName} {staff.LastName}' has no valid home building — every invited role requires one.");

        foreach (var student in Students)
        {
            if (student.SchoolIndex < 0 || student.SchoolIndex >= Schools.Length)
                throw new InvalidOperationException($"Demo roster: '{student.FirstName} {student.LastName}' is at building index {student.SchoolIndex}, which does not exist.");
            if (!GradesAt(student.SchoolIndex).Contains(student.Grade))
                throw new InvalidOperationException($"Demo roster: '{student.FirstName} {student.LastName}' is in grade {student.Grade.ToDisplay()}, which is not taught at '{Schools[student.SchoolIndex].Name}'.");
        }
    }

    /// <summary>The grades a building teaches, matching the <see cref="SchoolSpec.GradeRange"/> labels.</summary>
    public static GradeLevel[] GradesAt(int schoolIndex) => schoolIndex switch
    {
        Elementary => new[] { GradeLevel.K, GradeLevel.G1, GradeLevel.G2, GradeLevel.G3, GradeLevel.G4, GradeLevel.G5 },
        Middle => new[] { GradeLevel.G6, GradeLevel.G7, GradeLevel.G8 },
        _ => new[] { GradeLevel.G9, GradeLevel.G10, GradeLevel.G11, GradeLevel.G12 }
    };
}
